spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/myfptschool_dev?TimeZone=UTC
    username: root
    password: hiep2004

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  flyway:
    locations: classpath:db/migration,classpath:db/seed-dev

app:
  jwt:
    secret: dev-secret-key-change-in-production-must-be-at-least-256-bits
    expiration-ms: 86400000             # 24 giờ trong dev cho dễ test
